dead8309/Kizzy

app/src/main/res/values-pl/strings.xml
Translated newly added strings
=> Update Polish Translation

app/src/main/res/values-tr/strings.xml
translated newly added strings.
=> Update Turkish Translation

app/src/main/res/values-id/strings.xml
=> Update Indonesia Translation

app/src/main/res/values-ru/strings.xml, app/src/main/res/values/translations.xml
=> Fixed russian language a bit

app/src/main/res/values-ru/strings.xml
Hey! You can write me when you add new strings, МегаСвятой#9096
=> Update russian language

app/src/main/res/values-pl/strings.xml
Updated "contributors", "stream_url" and "stream_url_info"
=> Update Polish to 4.4

.idea/compiler.xml, data/src/test/kotlin/com/my/kizzy/data/KizzyRepositoryTest.kt, domain/src/main/java/com/my/kizzy/domain/model/user/User.kt, feature_profile/src/main/java/com/my/kizzy/feature_profile/ui/component/ProfileCard.kt, feature_settings/src/main/java/com/my/kizzy/feature_settings/Settings.kt
=> Show global_name instead of username

common/resources/src/main/res/values-pl/strings.xml
Now is rebranched so you can merge it
=> Update Polish language

common/resources/src/main/res/values-fa/strings.xml
Translated following strings:
- configs_directory
- custom_activity_type
- custom_activity_type_desc
- custom_activity_status
- custom_activity_status_desc
=> Update Farsi language

common/resources/src/main/res/values-vi/strings.xml
=> Update Vietnamese translation

common/resources/src/main/res/values-in/strings.xml
=> Update Indonesian Translaton

common/resources/src/main/res/values-th/strings.xml
just a lil bit update??? 
- idk -
เบอร์โทรอื่นจะได้ยินเสียงรอสาย แบบแบบแบบว่าให้รอ แต่เบอร์นี้จะได้ยินเสียงใจบอกว่า ท่านกำลังเข้าสู่บริการรับฝากหัวใจ
=> Update thai translation

feature_rpc_base/src/main/java/com/my/kizzy/feature_rpc_base/services/MediaRpcService.kt
As title.
I forgot to mark #296 as draft before committing 🥲
=> perf(media-rpc): prevent frequent socket messages from spamming actions

common/resources/src/main/res/values-de/strings.xml, common/resources/src/main/res/values-es/strings.xml, common/resources/src/main/res/values-fa/strings.xml, common/resources/src/main/res/values-fil/strings.xml, common/resources/src/main/res/values-fr/strings.xml, common/resources/src/main/res/values-hr/strings.xml, common/resources/src/main/res/values-in/strings.xml, common/resources/src/main/res/values-it/strings.xml, common/resources/src/main/res/values-ja/strings.xml, common/resources/src/main/res/values-kr/strings.xml, common/resources/src/main/res/values-mm/strings.xml, common/resources/src/main/res/values-nl/strings.xml, common/resources/src/main/res/values-pl/strings.xml, common/resources/src/main/res/values-pt/strings.xml, common/resources/src/main/res/values-ru/strings.xml, common/resources/src/main/res/values-th/strings.xml, common/resources/src/main/res/values-tr/strings.xml, common/resources/src/main/res/values-vi/strings.xml, common/resources/src/main/res/values-zh/strings.xml, common/resources/src/main/res/values/strings.xml, feature_console_rpc/src/main/java/com/my/kizzy/feature_console_rpc/GamesScreen.kt, feature_console_rpc/src/main/java/com/my/kizzy/feature_console_rpc/GamesViewModel.kt, feature_rpc_base/src/main/java/com/my/kizzy/feature_rpc_base/services/KizzyTileService.kt, feature_settings/src/main/java/com/my/kizzy/feature_settings/rpc_settings/RpcSettings.kt
=> chore(translation): add strings

app/src/main/AndroidManifest.xml, feature_home/src/main/java/com/my/kizzy/feature_home/Home.kt
- Open Kizzy on long pressing Kizzy Quickie
- Refresh Home page features when relaunching app in case user stops service via Quickie/notification
=> feat(quickie): launch app on hold

data/src/main/java/com/my/kizzy/data/get_current_data/media/MetadataResolver.kt
Small PR, just some nitpicking
=> chore(media-rpc): delocalize artist name

data/src/main/java/com/my/kizzy/data/rpc/KizzyRPC.kt
Probably not switch to DnD every time the presence updates lol
=> fix(rpc): persist chosen status

common/preference/src/main/java/com/my/kizzy/preference/Prefs.kt, common/resources/src/main/res/values-de/strings.xml, common/resources/src/main/res/values-es/strings.xml, common/resources/src/main/res/values-fa/strings.xml, common/resources/src/main/res/values-fil/strings.xml, common/resources/src/main/res/values-fr/strings.xml, common/resources/src/main/res/values-hr/strings.xml, common/resources/src/main/res/values-in/strings.xml, common/resources/src/main/res/values-it/strings.xml, common/resources/src/main/res/values-ja/strings.xml, common/resources/src/main/res/values-kr/strings.xml, common/resources/src/main/res/values-mm/strings.xml, common/resources/src/main/res/values-nl/strings.xml, common/resources/src/main/res/values-pl/strings.xml, common/resources/src/main/res/values-pt/strings.xml, common/resources/src/main/res/values-ru/strings.xml, common/resources/src/main/res/values-th/strings.xml, common/resources/src/main/res/values-tr/strings.xml, common/resources/src/main/res/values-vi/strings.xml, common/resources/src/main/res/values-zh/strings.xml, common/resources/src/main/res/values/strings.xml, data/src/main/java/com/my/kizzy/data/get_current_data/media/GetCurrentlyPlayingMedia.kt, data/src/main/java/com/my/kizzy/data/rpc/KizzyRPC.kt, data/src/main/java/com/my/kizzy/data/rpc/RpcImage.kt, feature_media_rpc/src/main/java/com/my/kizzy/feature_media_rpc/MediaRpc.kt, feature_rpc_base/src/main/java/com/my/kizzy/feature_rpc_base/Ext.kt, feature_rpc_base/src/main/java/com/my/kizzy/feature_rpc_base/services/MediaRpcService.kt
=> feat(media-rpc): option to show playback state

common/resources/src/main/res/values-de/strings.xml, common/resources/src/main/res/values-es/strings.xml, common/resources/src/main/res/values-fa/strings.xml, common/resources/src/main/res/values-fil/strings.xml, common/resources/src/main/res/values-fr/strings.xml, common/resources/src/main/res/values-hr/strings.xml, common/resources/src/main/res/values-in/strings.xml, common/resources/src/main/res/values-it/strings.xml, common/resources/src/main/res/values-ja/strings.xml, common/resources/src/main/res/values-kr/strings.xml, common/resources/src/main/res/values-mm/strings.xml, common/resources/src/main/res/values-nl/strings.xml, common/resources/src/main/res/values-pl/strings.xml, common/resources/src/main/res/values-pt/strings.xml, common/resources/src/main/res/values-ru/strings.xml, common/resources/src/main/res/values-th/strings.xml, common/resources/src/main/res/values-tr/strings.xml, common/resources/src/main/res/values-vi/strings.xml, common/resources/src/main/res/values-zh/strings.xml, common/resources/src/main/res/values/strings.xml, feature_logs/src/main/java/com/my/kizzy/feature_logs/LogScreen.kt
10 lines limit gets kinda stupidly annoying when you're trying to debug stuff
=> feat(logs): allow expand and copy on long click

common/preference/src/main/java/com/my/kizzy/preference/LangPrefs.kt, common/resources/src/main/res/values/translations.xml
- Sort language options based on locale, complying with [ICU](https://icu.unicode.org)'s locale format
- Import unused `kr` translation
=> chore(language): sort list by locale

common/resources/src/main/res/values-de/strings.xml, common/resources/src/main/res/values-es/strings.xml, common/resources/src/main/res/values-fa/strings.xml, common/resources/src/main/res/values-fil/strings.xml, common/resources/src/main/res/values-fr/strings.xml, common/resources/src/main/res/values-hr/strings.xml, common/resources/src/main/res/values-in/strings.xml, common/resources/src/main/res/values-it/strings.xml, common/resources/src/main/res/values-ja/strings.xml, common/resources/src/main/res/values-kr/strings.xml, common/resources/src/main/res/values-mm/strings.xml, common/resources/src/main/res/values-nl/strings.xml, common/resources/src/main/res/values-pl/strings.xml, common/resources/src/main/res/values-pt/strings.xml, common/resources/src/main/res/values-ru/strings.xml, common/resources/src/main/res/values-th/strings.xml, common/resources/src/main/res/values-tr/strings.xml, common/resources/src/main/res/values-vi/strings.xml, common/resources/src/main/res/values-zh/strings.xml, common/resources/src/main/res/values/strings.xml, feature_settings/src/main/java/com/my/kizzy/feature_settings/rpc_settings/RpcSettings.kt
- Update & format translatable strings
- Remove unused locale-only strings
=> chore: update strings

common/resources/src/main/res/values-kr/strings.xml, feature_profile/src/main/java/com/my/kizzy/feature_profile/ui/component/ProfileNetworkError.kt
| **Before** | **After** |
|------------|-----------|
| <img src="https://github.com/user-attachments/assets/c4adecce-74ec-47e7-8c1c-11b1bc7a3964" width="200" height="400" /> | <img src="https://github.com/user-attachments/assets/fb244a31-571e-4d60-a498-23e506a3544c" width="200" height="400" /> <img src="https://github.com/user-attachments/assets/1ce8c801-f781-4978-a418-7dff3195e607" width="200" height="400" /> |
Update Korean Translation
=> feat(ProfileNetworkError): Removed Error Message from Card Instead Using SnackBar & Dialog

feature_profile/src/main/java/com/my/kizzy/feature_profile/ui/component/ProfileNetworkError.kt
i forgot to make dialog can scrollable lol naw you can move these logic to root like you say at #349 which totally good idea
=> fix(ProfileNetworkError): make dialog scrollable and add top/bottom padding

common/resources/src/main/res/values-de/strings.xml, common/resources/src/main/res/values-es/strings.xml, common/resources/src/main/res/values-fa/strings.xml, common/resources/src/main/res/values-fil/strings.xml, common/resources/src/main/res/values-fr/strings.xml, common/resources/src/main/res/values-hr/strings.xml, common/resources/src/main/res/values-in/strings.xml, common/resources/src/main/res/values-it/strings.xml, common/resources/src/main/res/values-ja/strings.xml, common/resources/src/main/res/values-kr/strings.xml, common/resources/src/main/res/values-mm/strings.xml, common/resources/src/main/res/values-nl/strings.xml, common/resources/src/main/res/values-pl/strings.xml, common/resources/src/main/res/values-pt/strings.xml, common/resources/src/main/res/values-ru/strings.xml, common/resources/src/main/res/values-th/strings.xml, common/resources/src/main/res/values-tr/strings.xml, common/resources/src/main/res/values-vi/strings.xml, common/resources/src/main/res/values-zh/strings.xml, common/resources/src/main/res/values/strings.xml, feature_profile/src/main/java/com/my/kizzy/feature_profile/ui/component/DiscordLoginButton.kt, feature_profile/src/main/java/com/my/kizzy/feature_profile/ui/login/LoginScreen.kt
@dead8309 can you check this? maybe you want some enhancement, its based on #357 but looks like impossible to put into discord page
=> implement country-specific alert for VPN/DPI requirement
